apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-devops-bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-devops-bootcamp
  template:
    metadata:
      labels:
        app: agent-devops-bootcamp
    spec:
      containers:
      - name: agent-devops-bootcamp
        image: alerantdevopsbootcamp.azurecr.io/azure-agent/self-hosted-agent:1.0.0
        imagePullPolicy: Always
        env:
          - name: AZP_URL
            value: https://dev.azure.com/weid76
          - name: AZP_TOKEN
            value: bdetle5miz7sqeqvasb2xa6svwjksbl3jgc2vcdod2yscsihjirq
          - name: AZP_POOL
            value: Default
          - name: AZP_AGENT_NAME
            value: DevOps-BootCamp-Agent
      imagePullSecrets:
      - name: bootcamp-pull-secret
